[versions]
jetbrains-annotations = "26.0.2-1"
jspecify = "1.0.0"
luaj = "3.0.8-figura"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
luaj-jse = { module = "com.github.FiguraMC:luaj", version.ref = "luaj" }

[bundles]

[plugins]
